### ISSUE TITLE
Login problems 

### ISSUE THREAD

**Issue by tjakester** [chicago-justice-project/chicago-justice#31]
The error message I received is below. I tried to log in and got this error message. When i received it I hit back and hit log in again and it worked fine.  I am using Fire Fox with either the most up to date updates or very close. I am also on a Mac. 

Forbidden (403)

CSRF verification failed. Request aborted.

More information is available with DEBUG=True.

**Comment by meshulam** [comment]
@tjakester Have you seen this issue lately? If not let's close it.
