### ISSUE TITLE
Add column description to data dump

### ISSUE THREAD

**Issue by kbrose** [chicago-justice-project/chicago-justice#53]
At one point there was also a file [`column_names.txt`](https://github.com/chicago-justice-project/article-tagging/blob/master/lib/newstag/data/column_names.txt) that came with the data dump. Could that be added as well? Maybe something like

```bash
psql cjpweb_prd -h $DATABASE_URL -U cjpuser -c "\d *" > column_names.txt
```

? (UNTESTED! I know nothing about `psql`. Hacked that together from man pages.)

**Comment by meshulam** [comment]
^ pretty close!

**Comment by kbrose** [comment]
In case I come back to look at this years from now, the line was

```bash
psql cjpweb_prd -h $DATABASE_URL -U cjpuser -c "\\d $table" >> column_names.txt
```

(from 39b7eee31636ad52c65988391870e0ce79480f7b)
