### ISSUE TITLE
Table dump problems

### ISSUE THREAD

**Issue by kbrose** [chicago-justice-project/chicago-justice#55]
I think something is going wrong when dumping the tables? I downloaded the latest `.tar.gz` file (Updated 9//1/2017) from the sftp server, but when I try to extract it I get an error:

```
$ tar -xvzf cjp_tables.tgz 
cjp_tables/
cjp_tables/newsarticles_usercoding_categories.csv
cjp_tables/newsarticles_article.csv

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

Opening in archive manager shows two files:

* newsarticles_article.csv : a 1.4GB file (the previous data dump's version of this file was 2 GB)
* newsarticles_usercoding_categories.csv : a 0 byte file.

**Comment by meshulam** [comment]
I think it was the the disk filling up; I found a couple uncompressed exports from when we were testing the script changes. Deleted and re-ran the script and it looks good to me. Can you try downloading it again?

**Comment by kbrose** [comment]
Everything seems there now, thanks!
