### ISSUE TITLE
Create Scraper for Crime in Wrigleyville blog 

### ISSUE THREAD

**Issue by tjakester** [chicago-justice-project/chicago-justice#66]
http://www.cwbchicago.com/

Can we scrape this site?

Thanks!

Tracy

**Comment by mchladek** [comment]
Added with commit f1ccb1d79e10834f69e0821b7f1b41b600e8ac07 but still need to deploy on server. Will close issue when deployed.

**Comment by meshulam** [comment]
This has been deployed; verified the scraper is working as expected.
