### ISSUE TITLE
Restart nightly DB exports

### ISSUE THREAD

**Issue by kbrose** [chicago-justice-project/chicago-justice#74]
Now that this app has been migrated elastic beanstalk (:tada:), I'd love to get the nightly DB exports happening again.

(I'm mainly adding this issue so I have something to reference in the article-tagging's [CONTRIBUTING.md](https://github.com/chicago-justice-project/article-tagging/blob/master/CONTRIBUTING.md) file.)

**Comment by meshulam** [comment]
Fixed in #75 - this is deployed and running.
